#!/bin/sh


if [ -x /usr/bin/update-desktop-database ]; then
 update-desktop-database /usr/share/applications
fi

if [ -x /usr/bin/gtk-update-icon-cache ]; then
 gtk-update-icon-cache --force /usr/share/icons/hicolor
fi

#DEBHELPER#

exit 0
